title: Experience AI Challenge - Stage 5
hero_image: images/banner.png
description: The final stage of this quest is to submit your entry to the Experience AI showcase event. Once you submit your entry, your work will be looked at by a panel of experts and you’ll get feedback on your work, with special shortlisted entries being invited to a special showcase event!
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Create a model card
  - title: Complete the submission form
  - title: Quest Achieved!
